### ISSUE TITLE
Stepconf missing message

### ISSUE THREAD

**Issue by RinyVT** [thucke/TYPO3.ext.th_rating#57] opened 2019-09-11 10:35 UTC
Hi,

Every once in a while we get the following error message on the homepage of a pretty big website:
`Stepconf missing in ratingobject configuration of UID {uid} - check PID {pid}.`

It is because there is a ratingobject created for a tt_content element, but without stepconfs.
I did not find out yet on which tt_content element the ratingobject is created (since the uid of the element is not saved, and the ratingobject gets saved in a general storage pid), but I see the following code which might explain it:
https://github.com/thucke/TYPO3.ext.th_rating/blob/master/Classes/Domain/Repository/RatingobjectRepository.php#L72-L80
Which gets called by:
https://github.com/thucke/TYPO3.ext.th_rating/blob/master/Classes/Service/ExtensionHelperService.php#L204

It looks like the ratingobject is created there (if missing), but I see no further creation of the stepconfs.
Is this a bug or is there some configuration which should prevent this?

TYPO3: 8.7.27
th_rating: 1.6.1

Thanks in advance.

**Comment by thucke** [comment] 2019-09-29 15:20
Hi Riny,

thank you for asking.
Using the extension as a normal content element this behaviour is as intended.
The issue is that without any further configuration Rating AX does not know how many steps should be displayed for rating.

May I point you to the [manual](https://docs.typo3.org/p/thucke/th-rating/1.7/en-us/UsersManual/Index.html), step 3. This should help.

The storage page could be configured using the constant `plugin.tx_thrating.settings.pluginStoragePid` (ref: https://docs.typo3.org/p/thucke/th-rating/1.7/en-us/AdministratorManual/Constants/Index.html#pluginstoragepid).

One question please:
In the error message - do you see numbers instead of {uid} and {pid} or just the text?
If you see numbers then in BE on the page {pid} you should find the ratingobject `tt_content [uid]` where the ratingsteps are missing.
If the message still appears try to clear all caches or delete the file typo3temp/thratingDyn.css.

**Comment by RinyVT** [comment] 2019-10-10 10:41
Hi Thomas,

Thank you for your answer.
The error-message shows numbers instead of {uid} and {pid}, let's say it shows:
`Stepconf missing in ratingobject configuration of UID 123 - check PID 456.`
When I check in the folder `456` there is indeed a RatingObject, **but** no one has created this from the backend. There is no history of this element available thus it must have been created from the frontend.
The problem is, we cannot find where it is created. I have searched the whole database but there is no content element with the plugin from th_rating.

From time to time, there is a ratingobject created with:
Rating Object Tablename: tt_content
Rating Object Fieldname: uid
No stepconfs
One rating, with Rated Object Uid `123456`

Is the `123456` uid the uid of a content element? Because that content element is just a textpic element on a page that is disabled so I can't see how this is coming from that element.

Do you maybe have other ideas?
Thanks in advance.

**Comment by thucke** [comment] 2019-10-10 18:20
Thank you, Rhiny - you're on the right track.
The rating object was automatically created by the extension. 

If you include the extension as a backend content object this object get a uid. 
Then, if one gives a rating on this object the rating is counted on this uid.
Hence you're able to include multiple ratings on one page giving each seperate ratings.

Actually I don't have a glue where this rating on uid 12345 comes from.
But I'm pretty sure you'll get rid of that message if you just create at least one stepconf in the hierarchy of the mentioned rating object.

Give it a try
Greets
Thomas

**Comment by thucke** [comment] 2019-11-21 16:20
Hi @RinyVT,

would you plaese give me a short feedback if your issue has been solved?
Best would be closing this task in case.

Thank you
Thomas

**Comment by RinyVT** [comment] 2019-11-22 09:15
Hi Thomas,

Sorry for the late response.
The problem is what you also describe, we have no idea why the ratingobject is being created.
You are right that when we add stepconf to the object the error message disappears, but we don't want the ratingobject to be created in the first place.
We have no idea **when** or **why** the ratingobject is created, the mentioned uid is from a plugin within a storage folder that's not been used in years so that is very strange.

For now, I have disabled that content element (you never know), and will keep an eye out if the message returns. If so, I'll just have to create a very dirty fix to just delete or hide the ratingobject upon creation without stepconfs.

Thanks for now, if you have any more ideas where to look I would to love to hear them.

**Comment by thucke** [comment] 2019-11-25 16:25
Thank you Rhiny,

normally the ratingobect should be automatically created if the extension is added as a page content obect on any page (using 'plugin' content obect type in the backend).
I'll check if - caused by a bug - it's getting created every time you install the extension.

**Comment by thucke** [comment] 2020-02-02 15:57
Added a new configuration setting `showMissingStepconfError` to enable/disable the message in the frontend. Default is disabled. This will show up the error only in the extension logfile.
It's been verified that the default ratingobject ``tt_contenct[uid]`` is only automatically created if the extension has been placed on a page as a page content object using the ``Insert plugin`` content element type.

**Closed by thucke** 2020-02-02 15:57 UTC
Labels: Feedback needed
